name: Publish container image

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_image:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
    - name: Install NASM
      run: |
        sudo apt-get update
        sudo apt-get install nasm
    - name: Install cargo-binutils
      run: cargo install cargo-binutils
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: hermitcore
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build demo
      run: |
        cargo build --no-default-features -p rusty_demo --release
        cd loader
        make release=1
    - name: Create dockerfile
      run: |
        cat << END > Dockerfile
        FROM scratch
        COPY loader/target/x86_64-unknown-hermit-loader/release/rusty-loader hermit/rusty-loader
        COPY target/x86_64-unknown-hermit/release/rusty_demo hermit/rusty_demo
        CMD ["/hermit/rusty_demo"]
        END
    - name: Build and push container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/hermitcore/rusty_demo:latest
