name: Publish Docs

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rustup (apply rust-toolchain.toml)
        run: rustup show
      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install nasm
      - name: Generate documentation
        run: cargo doc -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit
      - name: Generate index.html
        run: |
          cat > target/x86_64-unknown-hermit/doc/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>Redirect!</title>
              <meta http-equiv="refresh" content="0; url=https://hermitcore.github.io/rusty-hermit/hermit_abi/" />
            </head>
            <body>
              <p><a href="https://hermitcore.github.io/rusty-hermit/hermit_abi/">Redirect</a></p>
            </body>
          </html>
          EOL
      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: target/x86_64-unknown-hermit/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
